# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

items = Item.create([{title: "GoPro HERO 5.0 MP", description: "Featuring stunning image quality and built-in Wi-Fi, HERO makes it simple to document and share life's most memorable moments. It captures 1080p30 video for gorgeous footage of every adventure. A variety of photo modes ensure your best shots yet - choose from 5MP single photos", image: "http://demandware.edgesuite.net/aasj_prd/on/demandware.static/Sites-GoPro-Site/Sites-gopro-products/default/dw9c8fee84/cam-represent/cam-represent-HERO3plusSilverNew.jpg", price: 399.99, inventory: 5},
                     {title: "Apple iPod Nano (7th Generation) - 16 GB - Blue", description: "About the size of a credit card, and just 5.4 mm thin, the new iPod nano is the thinnest iPod ever made. The 2.5-inch Multi-Touch display is nearly twice as big as the display", image: "http://store.storeimages.cdn-apple.com/4587/as-images.apple.com/is/image/AppleInc/aos/published/images/2/01/2012/ipodnano/2012-ipodnano-product-initial?wid=1200&hei=630&fmt=jpeg&qlt=95&op_sharpen=0&resMode=bicub&op_usm=0.5,0.5,0,0&iccEmbed=0&layer=comp&.v=1400799565463", price: 99.99, inventory: 4},
                     {title: "Dog Leash", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla.", image: "http://i.ebayimg.com/00/$T2eC16NHJFwFF,GE03H9BRY0ogRhMQ~~_35.JPG", price: 9.99, inventory: 300},
                     {title: "Environmentally Friendly Dog Bed", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.", image: "http://www.the-eco-market.com/wp-content/uploads/2014/04/environmentally-friendly-pet-supplies-4.jpg", price: 129.99, inventory: 3}])

category = Category.create([{name: "Electronics", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus", image: "http://sustainablog.org/wp-content/uploads/2012/02/home-electronics.jpg", rank:1},
                            {name: "Pets", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus", image: "https://chattacks.com/file/pic/photo/2014/02/Administrator-Chattacks:%20Pets%20&%20Animals%20Tack%20Category_1024.jpg", rank:1}])